---
- name: Play 
  hosts: localhost
#  connection: local
#  become: yes
  tasks:

    - name: Updating all the packages
      yum:
        name: '*'
        state: latest
        update_cache: yes
#    - name: Just force systemd to reread configs
#      systemd:
#        daemon_reload: true
#    - name: Update APT Cache and install few packages
#      apt:
#        update_cache: true
#        name: htop
##   comment to start execution on node
